/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weka.main;

import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import weka.data.Attribute;
import weka.data.DataStore;

/**
 *
 * @author visat
 */
public class MainFrame extends javax.swing.JFrame {
    private static final String TRAINING_FULL = "Full Training";
    private static final String TRAINING_N_FOLD = "N-Fold Training";

    private static final String ALGO_KNN = "kNN";
    private static final String ALGO_NAIVE_BAYES = "Naive Bayes";
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        buttonRun = new javax.swing.JButton();
        paneResult = new javax.swing.JScrollPane();
        textResult = new javax.swing.JTextArea();
        labelClass = new javax.swing.JLabel();
        comboClass = new javax.swing.JComboBox<>();
        labelFileName = new javax.swing.JLabel();
        textFileName = new javax.swing.JTextField();
        buttonFileName = new javax.swing.JButton();
        comboAlgorithm = new javax.swing.JComboBox<>();
        labelAlgorithm = new javax.swing.JLabel();
        spinnerAlgorithm = new javax.swing.JSpinner();
        labelTraining = new javax.swing.JLabel();
        comboTraining = new javax.swing.JComboBox<>();
        spinnerTraining = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonRun1 = new javax.swing.JButton();
        labelClass1 = new javax.swing.JLabel();
        comboClass1 = new javax.swing.JComboBox<>();
        labelFileName1 = new javax.swing.JLabel();
        textFileName1 = new javax.swing.JTextField();
        buttonFileName1 = new javax.swing.JButton();
        comboAlgorithm1 = new javax.swing.JComboBox<>();
        labelAlgorithm1 = new javax.swing.JLabel();
        spinnerAlgorithm1 = new javax.swing.JSpinner();
        labelTraining1 = new javax.swing.JLabel();
        comboTraining1 = new javax.swing.JComboBox<>();
        spinnerTraining1 = new javax.swing.JSpinner();
        paneResult1 = new javax.swing.JScrollPane();
        textResult1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WEKA-WEKA");
        setName("mainFrame"); // NOI18N

        buttonRun.setText("Run");
        buttonRun.setEnabled(false);
        buttonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRunActionPerformed(evt);
            }
        });

        textResult.setEditable(false);
        textResult.setColumns(20);
        textResult.setRows(5);
        paneResult.setViewportView(textResult);

        labelClass.setText("Choose class:");

        comboClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClassActionPerformed(evt);
            }
        });

        labelFileName.setText("File name:");

        textFileName.setEditable(false);
        textFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFileNameActionPerformed(evt);
            }
        });

        buttonFileName.setText("...");
        buttonFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileNameActionPerformed(evt);
            }
        });

        comboAlgorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ALGO_KNN, ALGO_NAIVE_BAYES }));
        comboAlgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlgorithmActionPerformed(evt);
            }
        });

        labelAlgorithm.setText("Algorithm:");

        spinnerAlgorithm.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));

        labelTraining.setText("Training Schema:");

        comboTraining.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { TRAINING_N_FOLD, TRAINING_FULL }));
        comboTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTrainingActionPerformed(evt);
            }
        });

        spinnerTraining.setModel(new javax.swing.SpinnerNumberModel(10, 1, 100, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneResult)
                    .addComponent(comboClass, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textFileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFileName)
                            .addComponent(buttonRun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTraining)
                            .addComponent(labelClass)
                            .addComponent(labelAlgorithm))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboTraining, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboAlgorithm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerAlgorithm)
                            .addComponent(spinnerTraining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlgorithm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTraining)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTraining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerTraining, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRun)
                .addGap(18, 18, 18)
                .addComponent(paneResult, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        buttonRun1.setText("Run");
        buttonRun1.setEnabled(false);
        buttonRun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRun1ActionPerformed(evt);
            }
        });

        labelClass1.setText("Choose the attribute class:");

        comboClass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClass1ActionPerformed(evt);
            }
        });

        labelFileName1.setText("File name:");

        textFileName1.setEditable(false);
        textFileName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFileName1ActionPerformed(evt);
            }
        });

        buttonFileName1.setText("...");
        buttonFileName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileName1ActionPerformed(evt);
            }
        });

        comboAlgorithm1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ALGO_KNN, ALGO_NAIVE_BAYES }));
        comboAlgorithm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlgorithm1ActionPerformed(evt);
            }
        });

        labelAlgorithm1.setText("Algorithm:");

        spinnerAlgorithm1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        spinnerAlgorithm1.setName("spinneralgorithm1"); // NOI18N

        labelTraining1.setText("Training Schema:");

        comboTraining1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { TRAINING_N_FOLD, TRAINING_FULL }));
        comboTraining1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTraining1ActionPerformed(evt);
            }
        });

        spinnerTraining1.setModel(new javax.swing.SpinnerNumberModel(10, 1, 100, 1));

        textResult1.setEditable(false);
        textResult1.setColumns(20);
        textResult1.setRows(5);
        paneResult1.setViewportView(textResult1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneResult1)
                    .addComponent(comboClass1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textFileName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFileName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboTraining1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboAlgorithm1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerAlgorithm1)
                            .addComponent(spinnerTraining1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFileName1)
                            .addComponent(buttonRun1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTraining1)
                            .addComponent(labelClass1)
                            .addComponent(labelAlgorithm1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox7, 0, 104, Short.MAX_VALUE)
                            .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFileName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFileName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFileName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlgorithm1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAlgorithm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerAlgorithm1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTraining1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTraining1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerTraining1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelClass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboClass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(buttonRun1)
                .addGap(18, 18, 18)
                .addComponent(paneResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileNameActionPerformed
        final JFileChooser fileDialog = new JFileChooser();
        int returnVal = fileDialog.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String fileName = fileDialog.getSelectedFile().getPath();
            textFileName.setText(fileName);
            comboClass.removeAllItems();
            DataStore ds = new DataStore();
            ds.readArff(fileName);
            ds.read();
            for (Attribute attr: ds.getArffAttributes())
                comboClass.addItem(attr.getName());            
            if (ds.getElementSize() > 0)
                spinnerAlgorithm.setModel(new SpinnerNumberModel(1, 1, ds.getElementSize(), 1));
            comboClass.setSelectedIndex(comboClass.getItemCount() - 1);
            buttonRun.setEnabled(true);
        }
    }//GEN-LAST:event_buttonFileNameActionPerformed

    private void comboAlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlgorithmActionPerformed
        String algorithm = (String)comboAlgorithm.getSelectedItem();
        if (algorithm.equalsIgnoreCase("kNN"))
            spinnerAlgorithm.setVisible(true);
        else
            spinnerAlgorithm.setVisible(false);
    }//GEN-LAST:event_comboAlgorithmActionPerformed

    private void comboTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTrainingActionPerformed
        String training = (String)comboTraining.getSelectedItem();
        if (training.equalsIgnoreCase("N-Fold Training"))
            spinnerTraining.setVisible(true);
        else
            spinnerTraining.setVisible(false);
    }//GEN-LAST:event_comboTrainingActionPerformed

    private void buttonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRunActionPerformed
        int algorithm = 1;
        switch ((String)comboAlgorithm.getSelectedItem()) {
            case ALGO_KNN:
                algorithm = 1;
                break;
            case ALGO_NAIVE_BAYES:
                algorithm = 2;
                break;
        }
        int training = 1;
        switch ((String)comboTraining.getSelectedItem()) {
            case TRAINING_FULL:
                training = 1;
                break;
            case TRAINING_N_FOLD:
                training = 2;
                break;
        }
        textResult.setText(Main.doAlgorithm(
                algorithm, training, textFileName.getText(),
                (int)spinnerAlgorithm.getValue(), (int)spinnerTraining.getValue(),
                comboClass.getSelectedIndex()));
    }//GEN-LAST:event_buttonRunActionPerformed

    private void textFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFileNameActionPerformed

    private void buttonRun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRun1ActionPerformed
        int algorithm = 1;
        switch ((String)comboAlgorithm.getSelectedItem()) {
            case ALGO_KNN:
                algorithm = 1;
                break;
            case ALGO_NAIVE_BAYES:
                algorithm = 2;
                break;
        }
        int training = 1;
        switch ((String)comboTraining.getSelectedItem()) {
            case TRAINING_FULL:
                training = 1;
                break;
            case TRAINING_N_FOLD:
                training = 2;
                break;
        }
        textResult.setText(Main.doAlgorithm(
                algorithm, training, textFileName.getText(),
                (int)spinnerAlgorithm.getValue(), (int)spinnerTraining.getValue(),
                comboClass.getSelectedIndex()));
    }//GEN-LAST:event_buttonRun1ActionPerformed

    private void textFileName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFileName1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textFileName1ActionPerformed

    private void buttonFileName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileName1ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fileDialog = new JFileChooser();
        int returnVal = fileDialog.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String fileName = fileDialog.getSelectedFile().getPath();
            textFileName1.setText(fileName);
            comboClass1.removeAllItems();
            DataStore ds = new DataStore();
            ds.readArff(fileName);
            ds.read();
            for (Attribute attr: ds.getArffAttributes())
                comboClass1.addItem(attr.getName());            
            if (ds.getElementSize() > 0)
                spinnerAlgorithm1.setModel(new SpinnerNumberModel(1, 1, ds.getElementSize(), 1));
            comboClass1.setSelectedIndex(comboClass1.getItemCount() - 1);
            buttonRun1.setEnabled(true);
        }
    }//GEN-LAST:event_buttonFileName1ActionPerformed

    private void comboAlgorithm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlgorithm1ActionPerformed
        String algorithm = (String)comboAlgorithm1.getSelectedItem();
        if (algorithm.equalsIgnoreCase("kNN"))
            spinnerAlgorithm1.setVisible(true);
        else
            spinnerAlgorithm1.setVisible(false);
    }//GEN-LAST:event_comboAlgorithm1ActionPerformed

    private void comboTraining1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTraining1ActionPerformed
        String training = (String)comboTraining1.getSelectedItem();
        if (training.equalsIgnoreCase("N-Fold Training"))
            spinnerTraining1.setVisible(true);
        else
            spinnerTraining1.setVisible(false);
    }//GEN-LAST:event_comboTraining1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       String training = (String)comboTraining1.getSelectedItem(); 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void comboClass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClass1ActionPerformed

    private void comboClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClassActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(
                UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainFrame frame = new MainFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFileName;
    private javax.swing.JButton buttonFileName1;
    private javax.swing.JButton buttonRun;
    private javax.swing.JButton buttonRun1;
    private javax.swing.JComboBox<String> comboAlgorithm;
    private javax.swing.JComboBox<String> comboAlgorithm1;
    private javax.swing.JComboBox<String> comboClass;
    private javax.swing.JComboBox<String> comboClass1;
    private javax.swing.JComboBox<String> comboTraining;
    private javax.swing.JComboBox<String> comboTraining1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAlgorithm;
    private javax.swing.JLabel labelAlgorithm1;
    private javax.swing.JLabel labelClass;
    private javax.swing.JLabel labelClass1;
    private javax.swing.JLabel labelFileName;
    private javax.swing.JLabel labelFileName1;
    private javax.swing.JLabel labelTraining;
    private javax.swing.JLabel labelTraining1;
    private javax.swing.JScrollPane paneResult;
    private javax.swing.JScrollPane paneResult1;
    private javax.swing.JSpinner spinnerAlgorithm;
    private javax.swing.JSpinner spinnerAlgorithm1;
    private javax.swing.JSpinner spinnerTraining;
    private javax.swing.JSpinner spinnerTraining1;
    private javax.swing.JTextField textFileName;
    private javax.swing.JTextField textFileName1;
    private javax.swing.JTextArea textResult;
    private javax.swing.JTextArea textResult1;
    // End of variables declaration//GEN-END:variables
}
